[package]
name = "map_generation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_ecs_tilemap = "0.16.0"
noise = { workspace = true }
assets = { path = "../assets" }
camera = { path = "../camera" }
common = { path = "../common" }